name: CI/CD Pipeline

# Este workflow se ejecutará cada vez que hagas un push a la rama 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: CONSTRUIR Y SUBIR IMAGEN (CI)
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código (Checkout)
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen (Build & Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Usamos 'latest' para que Render siempre busque la versión más reciente
          tags: ${{ secrets.DOCKER_USERNAME }}/hola-devops:latest

  # TRABAJO 2: DESPLEGAR EN RENDER (CD)
  deploy-to-render:
    needs: build-and-push # Espera a que termine el trabajo anterior
    runs-on: ubuntu-latest
    steps:
      - name: Disparar despliegue en Render
        # Usamos curl para llamar a la API de Render y avisar que hay una nueva imagen
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'